/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.stewseo.examples;

import io.github.stewseo.yelp.fusion.client.yelpfusion.YelpFusionClient;
import io.github.stewseo.yelp.fusion.client.yelpfusion.business.Business;
import io.github.stewseo.yelp.fusion.client.yelpfusion.business.details.BusinessDetailsResponse;
import io.github.stewseo.yelp.fusion.client.yelpfusion.business.search.SearchBusiness;
import io.github.stewseo.yelp.fusion.client.yelpfusion.business.search.SearchBusinessResponse;
import io.github.stewseo.yelp.fusion.client.yelpfusion.categories.Categories;
import io.github.stewseo.yelp.fusion.client.yelpfusion.misc.AutoCompleteResponse;

import java.util.ArrayList;
import java.util.List;

public class Example {

    public static void main(String[] args) throws Exception {
        String apiKey = System.getenv("YELP_API_KEY");

        YelpFusionClient yelpClient = YelpFusionClient.createClient(apiKey);

        // Autocomplete
        AutoCompleteResponse response = yelpClient.autocomplete(a -> a.text("sush"));

        System.out.println("AutoCompleteResponse: " + response.categories() + "\n " + response.terms() + "\n " + response.businesses());


        String resultAlias = response.categories().get(0).alias();

        // CategoriesAlias
        Categories category = yelpClient.categories().alias(a -> a
                        .alias(resultAlias)
                )
                .category();

        System.out.println("CategoriesAliasResponse: " + category);

        String parent = category.parent_aliases().get(0);
        String cat = category.alias();

        Integer offset = 0;

        // Search Businesses
        SearchBusinessResponse searchResponse = yelpClient.businesses().businessSearch(s -> s
                .categories(c -> c
                        .alias(cat))
                .term(parent)
                .limit(50)
                .offset(offset)
                .location("sanfrancisco"));

        System.out.println("SearchBusinessResponse: " + searchResponse.region() + ", total: " + searchResponse.total());

        List<Business> businesses = new ArrayList<>();

        for(SearchBusiness business: searchResponse.businesses()) {
            String id = business.id();
            // Business Details
            BusinessDetailsResponse busDetailsResp = yelpClient.businesses().businessDetails(s -> s.id(id));
            businesses.add(busDetailsResp.result().get(0));
        }

        System.out.println("number of businesses: " + businesses.size());
    }
}
